### ISSUE TITLE
[1주차 12월29일 ~ 1월4일] 박준호 TODO

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#1]
### 
- [x] url 단축 알고리즘 구현
- [x] 네이버 클라우드 플랫폼 서버 개설
- [x] url 단축 시 사용되는 숫자 구현 방법 도출

**Comment by aj1155** [comment]
화이팅!!
