### ISSUE TITLE
[8주차 2월 18일 ~ 2월24일] 박준호 TODO

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#102]
- [x] 넥스터즈 나이트 행사 때 급하게 했던 부분 코드 리팩토링
- [x] QA 맡은 부분 맥(크롬), 아이폰
- [x] 서버 로그 에러 혹은 의심스러운 것들 체크

**Comment by JunHoPark93** [comment]
https://www.nexters.me/Yb
