### ISSUE TITLE
[3주차 1월14일 ~ 1월20일] 박준호 TODO

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#21]
- [x] 메인 요청 통계 기능
- [x] 각종 에러 처리
- [x] 테스트 검토
- [x] 통계 기능 논의
