### ISSUE TITLE
[4주차 1월 21일 ~ 1월27일] 박준호 TODO

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#35]
- [x] 3주차 리팩토링
- [x] 비효율적인 로직 개선
- [x] 통계 서버 생성
- [x] 기타 필요한 부분 공부
