### ISSUE TITLE
[TODO] 2월 10일 ~ 2월 16일 계획

### ISSUE THREAD

**Issue by choitaehoon** [URL-CHOP/Chop-Api#80]
- [x] RestTemplate으로 title 가져오기
- [x] ncloud 서버 만들기 
- [x] 통계 로그 설정 잡고 pr 날리기
