### ISSUE TITLE
[7주차 2월 11일 ~ 2월17일] 박준호 TODO

### ISSUE THREAD

**Issue by JunHoPark93** [URL-CHOP/Chop-Api#89]
- [x] 통계 서버 mybatis 기능 구현
- [x] 앱 서버 rest - grpc 통신 부분 수정 (반환 형식 등)
- [x] 레퍼러, 플랫폼 정규식 태훈이랑 같이 구현

**Comment by JunHoPark93** [comment]
done
