### ISSUE TITLE
[2주차 1월6일 ~ 1월13일] 최태훈 TODO  

### ISSUE THREAD

**Issue by choitaehoon** [URL-CHOP/Chop-Api#9]
<h1>TODO</h1>

- [ ] 통계 기능 구현하기
- [ ] 통계 기능 junit5 구현
- [ ]  준호형 코드와 합친 후 실행 시키기

**Comment by aj1155** [comment]
통계는 태훈아
현재 https://www.nexters.me/abcde 라는 단축 url이 있다고 하면
요 url이 얼마나 사용됬는지, 그리고 이 url을 어디서 들어오는지(ex naver, google, kakao 등등 이 전 경로)
일단 요거 2개 해보자
